export const MOCK_PHOTO_LIST = [
  {
    albumId: 1,
    id: 1,
    title: 'accusamus beatae ad facilis cum similique qui sunt',
    url: 'https://via.placeholder.com/600/92c952',
    thumbnailUrl: 'https://via.placeholder.com/150/92c952',
  },
  {
    albumId: 1,
    id: 2,
    title: 'reprehenderit est deserunt velit ipsam',
    url: 'https://via.placeholder.com/600/771796',
    thumbnailUrl: 'https://via.placeholder.com/150/771796',
  },
  {
    albumId: 1,
    id: 3,
    title: 'officia porro iure quia iusto qui ipsa ut modi',
    url: 'https://via.placeholder.com/600/24f355',
    thumbnailUrl: 'https://via.placeholder.com/150/24f355',
  },
  {
    albumId: 2,
    id: 51,
    title: 'non sunt voluptatem placeat consequuntur rem incidunt',
    url: 'https://via.placeholder.com/600/8e973b',
    thumbnailUrl: 'https://via.placeholder.com/150/8e973b',
  },
  {
    albumId: 3,
    id: 101,
    title: 'incidunt alias vel enim',
    url: 'https://via.placeholder.com/600/e743b',
    thumbnailUrl: 'https://via.placeholder.com/150/e743b',
  },
  {
    albumId: 4,
    id: 151,
    title: 'possimus dolor minima provident ipsam',
    url: 'https://via.placeholder.com/600/1d2ad4',
    thumbnailUrl: 'https://via.placeholder.com/150/1d2ad4',
  },
  {
    albumId: 5,
    id: 201,
    title: 'nesciunt dolorum consequatur ullam tempore accusamus debitis sit',
    url: 'https://via.placeholder.com/600/250289',
    thumbnailUrl: 'https://via.placeholder.com/150/250289',
  },
  {
    albumId: 6,
    id: 251,
    title: 'voluptatibus nihil a',
    url: 'https://via.placeholder.com/600/afc5c2',
    thumbnailUrl: 'https://via.placeholder.com/150/afc5c2',
  },
  {
    albumId: 7,
    id: 301,
    title: 'aspernatur est omnis qui laudantium illo in laborum dolore',
    url: 'https://via.placeholder.com/600/92ce9a',
    thumbnailUrl: 'https://via.placeholder.com/150/92ce9a',
  },
  {
    albumId: 8,
    id: 351,
    title: 'molestias debitis cum',
    url: 'https://via.placeholder.com/600/9ae7cb',
    thumbnailUrl: 'https://via.placeholder.com/150/9ae7cb',
  },
  {
    albumId: 9,
    id: 401,
    title: 'vitae et cumque velit repellat eaque',
    url: 'https://via.placeholder.com/600/9f134c',
    thumbnailUrl: 'https://via.placeholder.com/150/9f134c',
  },
  {
    albumId: 10,
    id: 451,
    title: 'dolorem accusantium corrupti incidunt quas ex est',
    url: 'https://via.placeholder.com/600/5e912a',
    thumbnailUrl: 'https://via.placeholder.com/150/5e912a',
  },
];

export const MOCK_PHOTO = {
  albumId: 1,
  id: 1,
  title: 'accusamus beatae ad facilis cum similique qui sunt',
  url: 'https://via.placeholder.com/600/92c952',
  thumbnailUrl: 'https://via.placeholder.com/150/92c952',
};
